name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Build macOS
        run: set -o pipefail && xcodebuild -skipMacroValidation -scheme LayerDefence build -destination "generic/platform=macOS,arch=arm64,variant=macOS" | xcpretty
